# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Lint swift code."
  lane :enforce_swift_style do
    swiftlint(
      # mode: :autocorrect,
      files: [
        "#{Dir.pwd}/../Sources/VSRegex.swift",
        "#{Dir.pwd}/../VSRegexTest/TestDataFetcher.swift",
        "#{Dir.pwd}/../VSRegexTest/VSRegexTest.swift",
      ],
      ignore_exit_status: true,
    )
  end
end
